version: '3.1'
services:
  postgres:
    restart: always
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

#  adminer uses a wrong socket, so it fails to connect
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080